### ISSUE TITLE
ipv6  问题

### ISSUE THREAD

**Issue by qist** [MetaCubeX/Clash.Meta#272]
建议IPv6 ip 可以关闭。这样纯IPV4 环境就不会出现dns 解析到IPV6然后无法连接的问题。然后IPV6 子网可以更改。

**Comment by wwqgtxx** [comment]
首先ipv6子网本来就是可以改的，其次就算解析的ipv6绝大部分应用也有ipv6 fallback功能，最后clash的dns默认也没开启ipv6解析的功能

**Comment by qist** [comment]
今天发的版本就出现一直连接IPV6 地址。ipv4 就出现不稳定现象。

**Comment by wwqgtxx** [comment]
自己去在配置文件里设置`ipv6: false`呀

**Comment by qist** [comment]
并没生效

**Comment by wwqgtxx** [comment]
根层级和`dns`层级下面都要设置

**Comment by qist** [comment]
是程序崩溃掉
版本 ：Clash.Meta-windows-amd64-alpha-2994fd5
```
time="2022-11-24T12:41:48+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) [fdfe:dcba:9876::1]:7709 --> [240e:e1:a900:10::91]:443 error: ip version error"
time="2022-11-24T12:41:48+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/CN) [fdfe:dcba:9876::1]:7715 --> [2409:8c1e:75b0:13::7b]:8080 error: ip version error"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x17f755f]

goroutine 692 [running]:
github.com/Dreamacro/clash/tunnel/statistic.NewTCPTracker({0x0, 0x0}, 0xc0000d01e0, 0xc0009f0ee0, {0x1cce0f0, 0xc00027a8c0})
        github.com/Dreamacro/clash/tunnel/statistic/tracker.go:77 +0x17f
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x1cc7e40, 0xc005600990})
        github.com/Dreamacro/clash/tunnel/tunnel.go:377 +0x512
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:161 +0x71
```

**Comment by wwqgtxx** [comment]
2994fd5版本已经撤回了，请用最新版本

**Comment by qist** [comment]
ok
