### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CopyOnceAgain** [MetaCubeX/Clash.Meta#560]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash.meta-android-arm64-cgo-alpha-872a28a

### Clash config

```yaml
默认配置
```

### Clash log

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63e9e56f58]

goroutine 176183 [running]:
github.com/Dreamacro/clash/tunnel.handleUDPToLocal({0x739bcb11f8, 0x401f2c5590}, {0x63ea7c5490, 0x400a579620}, {0x4013410528?, 0x400a5791d0?}, {{0x0?, 0x4000f90780?}, 0x4000122018?}, {{0x0?, ...}, ...})
	github.com/Dreamacro/clash/tunnel/connection.go:58 +0x378
created by github.com/Dreamacro/clash/tunnel.handleUDPConn.func2
	github.com/Dreamacro/clash/tunnel/tunnel.go:389 +0x98c
```

### Description

运行半小时左右会核心会崩溃  一定复现

**Comment by CopyOnceAgain** [comment]
clash.meta-android-arm64-cgo-alpha-daaf820 换了最新的阿尔法核心已经没问题了
