### ISSUE TITLE
[Bug] Crashes when configured to use Shadowsocks with Extensible Identity Header

### ISSUE THREAD

**Issue by shvchk** [MetaCubeX/Clash.Meta#627]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta v1.14.5 linux amd64 with go1.20.4 Sat Jun  3 10:11:59 UTC 2023

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
socks-port: 1080
allow-lan: false
external-controller: 127.0.0.1:9090

log-level: debug
mode: rule

dns:
  enable: true
  enhanced-mode: fake-ip

  default-nameserver:
   - 1.1.1.1
   - 8.8.8.8
   - 9.9.9.9

  nameserver:
    - tls://1.1.1.1
    - tls://1.0.0.1


proxies:
  - name: proxy
    type: ss
    server: proxy.example.com
    port: 8388
    cipher: 2022-blake3-chacha20-poly1305
    password: 'random/server/password=:random/user/password='
    client-fingerprint:
      chrome


rules:
  - DOMAIN,test-doamin.com,proxy
  - MATCH,DIRECT
```

### Clash log

```shell
INFO[2023-06-18T05:54:22] Start initial configuration in progress
INFO[2023-06-18T05:54:22] Geodata Loader mode: memconservative
INFO[2023-06-18T05:54:22] Initial configuration complete, total time: 0ms
INFO[2023-06-18T05:54:22] RESTful API listening at: 127.0.0.1:9090
INFO[2023-06-18T05:54:22] Sniffer is closed
INFO[2023-06-18T05:54:22] SOCKS proxy listening at: 127.0.0.1:1080
INFO[2023-06-18T05:54:22] Start initial compatible provider default
DEBU[2023-06-18T05:54:27] [Rule] use default rules
DEBU[2023-06-18T05:54:27] [DNS] resolve proxy.example.com from tls://1.0.0.1:853
DEBU[2023-06-18T05:54:27] [DNS] resolve proxy.example.com from tls://1.1.1.1:853
DEBU[2023-06-18T05:54:27] [DNS] resolve proxy.example.com from tls://1.1.1.1:853
DEBU[2023-06-18T05:54:27] [DNS] resolve proxy.example.com from tls://1.0.0.1:853
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc5ea19]

goroutine 22 [running]:
github.com/metacubex/sing-shadowsocks2/shadowaead_2022.(*Method).writeExtendedIdentityHeaders(0xc0000dd680, 0xc00011a310?, {0xc000460400, 0x20, 0x0?})
        github.com/metacubex/sing-shadowsocks2@v0.0.0-20230529235701-a238874242ca/shadowaead_2022/method.go:260 +0x219
github.com/metacubex/sing-shadowsocks2/shadowaead_2022.(*clientConn).writeRequest(0xc00012e780, {0x0, 0x0, 0x0})
        github.com/metacubex/sing-shadowsocks2@v0.0.0-20230529235701-a238874242ca/shadowaead_2022/method.go:198 +0x299
github.com/metacubex/sing-shadowsocks2/shadowaead_2022.(*Method).DialConn(0xc0000dd680, {0x1666a30?, 0xc00011a310}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000048fa0, 0xb}})
        github.com/metacubex/sing-shadowsocks2@v0.0.0-20230529235701-a238874242ca/shadowaead_2022/method.go:135 +0xe5
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocks).StreamConnContext(0xc00009ba90, {0x1659948?, 0xc000127530?}, {0x1666a30?, 0xc00011a310?}, 0xc0000d8a00)
        github.com/Dreamacro/clash/adapter/outbound/shadowsocks.go:128 +0x866
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocks).DialContextWithDialer(0xc00009ba90, {0x1659948, 0xc000127530}, {0x1654738?, 0xc000090300?}, 0x11c0cc0?)
        github.com/Dreamacro/clash/adapter/outbound/shadowsocks.go:155 +0x267
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocks).DialContext(0xc00009ba90, {0x1659948, 0xc000127530}, 0x50?, {0x0?, 0xc000159ad8?, 0x40db2a?})
        github.com/Dreamacro/clash/adapter/outbound/shadowsocks.go:134 +0xf6
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x10?, {0x1659948?, 0xc000127530?}, 0x7fc5b169f268?, {0x0?, 0xc000159b20?, 0x40db2a?})
        github.com/Dreamacro/clash/adapter/adapter.go:41 +0x30
github.com/Dreamacro/clash/tunnel.handleTCPConn.func3({0x1659948?, 0xc000127530})
        github.com/Dreamacro/clash/tunnel/tunnel.go:451 +0x9f
github.com/Dreamacro/clash/tunnel.retry[...]({0x1659948?, 0xc000127530}, 0xc000477f70, 0xc000477f00)
        github.com/Dreamacro/clash/tunnel/tunnel.go:625 +0xd1
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x16562e0, 0xc00005c020})
        github.com/Dreamacro/clash/tunnel/tunnel.go:450 +0x64c
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:210 +0x112
```

### Description

See [Shadowsocks Extensible Identity Header spec](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-2-shadowsocks-2022-extensible-identity-headers.md) and [example config](https://github.com/shadowsocks/shadowsocks-rust#configuration)

Server: shadowsocks-rust
Server config:
```json
    ...
    {
      "server": "::",
      "server_port": 8388,
      "method": "2022-blake3-chacha20-poly1305",
      "password": "random/server/password=",
      "users": [
          {
            "name": "test",
            "password": "random/user/password="
          }
      ],
    }
    ...
```

Of course, passwords are actually generated with `ssservice genkey -m 2022-blake3-chacha20-poly1305`.

**Comment by asinitial** [comment]
It seems that Mihomo still doesn't support Shadowsocks with Extensible Identity Header. The client process doesn't crash anymore, but connecting to the server unsuccessfully.

### **Server log**

```
Aug 02 02:40:42 debian shadowsocks-rust.ssserver-daemon[227644]: 2026/08/02 02:40:42 tcp:***.***.***.***:22529 accepted tcp:127.0.0.1:0
Aug 02 02:40:42 debian shadowsocks-rust.ssserver-daemon[227621]: 2026-08-02T02:40:42.256750063+08:00  WARN tcp handshake failed. peer: [::1]:42412, decrypt header chunk failed
```
