### ISSUE TITLE
clash for windows 替换为meta内核，间歇性崩溃。

### ISSUE THREAD

**Issue by yoohooyoo** [MetaCubeX/Clash.Meta#712]
clash for windows 替换为meta内核，间歇性崩溃。
重启cfw后崩溃消失，但隔几天出现一次。
meta、cfw均为最新版。

日志如下：
```
goroutine 198694 [running]:
github.com/metacubex/quic-go.(*connMultiplexer).AddConn(0xc001580340, {0x1c9ed9885c8?, 0xc00981c628?})
	github.com/metacubex/quic-go@v0.37.4-0.20230809092428-5acf8eb2de86/multiplexer.go:59 +0x165
github.com/metacubex/quic-go.(*Transport).init.func1()
	github.com/metacubex/quic-go@v0.37.4-0.20230809092428-5acf8eb2de86/transport.go:220 +0x362
sync.(*Once).doSlow(0x20?, 0xc000bd1568?)
	sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	sync/once.go:65
github.com/metacubex/quic-go.(*Transport).init(0xc004e527e0, 0x40?)
	github.com/metacubex/quic-go@v0.37.4-0.20230809092428-5acf8eb2de86/transport.go:186 +0x4d
github.com/metacubex/quic-go.(*Transport).Dial(0xc004e527e0, {0x14d96e8, 0x1e72b80}, {0x14d05c8?, 0xc0030a7ce0}, 0x3?, 0x14d05c8?)
	github.com/metacubex/quic-go@v0.37.4-0.20230809092428-5acf8eb2de86/transport.go:155 +0x9a
github.com/Dreamacro/clash/transport/hysteria/transport.(*ClientTransport).QUICDial(0x1e72b80?, {0xc004686488, 0x3}, {0xc005d8c558?, 0xffff?}, {0xc004686435, 0xb}, 0xc0015ef790?, 0x5109f7?, {0x0, ...}, ...)
	github.com/Dreamacro/clash/transport/hysteria/transport/client.go:82 +0x1e5
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).connectToServer(0xc0000f7000, {0x14d6a50?, 0xc00019fe80?})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go:78 +0x9a
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).openStreamWithReconnect(0xc0000f7000, {0x14d6a50, 0xc00019fe80})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go:172 +0xf8
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).DialTCP(0xc0000f7000, {0xc007a547e0?, 0xeec196?}, {0x14d6a50, 0xc00019fe80})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go:202 +0x7a
github.com/Dreamacro/clash/adapter/outbound.(*Hysteria).DialContext(0xc004ee9758, {0x14d9840?, 0xc0072485b0}, 0x0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/outbound/hysteria.go:56 +0x1b2
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc006629aa0?, {0x14d9840?, 0xc0072485b0?}, 0xc0015efa40?, {0x0?, 0x60e9f3?, 0xc002b78e5d?})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/adapter/outboundgroup.(*Fallback).DialContext(0xc0014c0500, {0x14d9840, 0xc0072485b0}, 0x5109f7?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/outboundgroup/fallback.go:34 +0xbe
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x1c9eef13728?, {0x14d9840?, 0xc0072485b0?}, 0xc0001db800?, {0x0?, 0xc0015efb20?, 0x5109f7?})
	github.com/Dreamacro/clash/adapter/adapter.go:67 +0x2a
github.com/Dreamacro/clash/tunnel.handleTCPConn.func3({0x14d9840?, 0xc0072485b0?})
	github.com/Dreamacro/clash/tunnel/tunnel.go:454 +0x8c
github.com/Dreamacro/clash/tunnel.retry[...]({0x14d9840?, 0xc0072485b0}, 0xc000bd1f70, 0xc000bd1f00)
	github.com/Dreamacro/clash/tunnel/tunnel.go:627 +0xcc
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x14d7040, 0xc0067726a0})
	github.com/Dreamacro/clash/tunnel/tunnel.go:453 +0x630
created by github.com/Dreamacro/clash/tunnel.process in goroutine 8
	github.com/Dreamacro/clash/tunnel/tunnel.go:209 +0x116
```

**Comment by CHNJohnHK** [comment]
@yoohooyoo 换核了你跑 meta 还是 cfw 那边问都没答案

**Comment by yoohooyoo** [comment]
@CHNJohnHK 
恩，不过换核玩的人不少，而且这次报错日志还算清楚。
如果meta开发组愿意看下顺手解决了，对大家也是好事。

**Comment by cx330-007** [comment]
@yoohooyoo 直接跑核心

**Comment by xishang0128** [comment]
@yoohooyoo cfw换核心不提供支持

**Comment by Larvan2** [comment]
先尝试用最新内核

**Comment by NyaMisty** [comment]
以后贴日志的时候不要自以为是地删掉觉得多余的部分。

**Comment by yoohooyoo** [comment]
> 以后贴日志的时候不要自以为是地删掉觉得多余的部分。

1.其他是正常连接日志，涉及问题出错的部分我一点都没删除。
2.说话不带刺也能表达清楚的。
