### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4118] with capacity 4096

### ISSUE THREAD

**Issue by LitingLin** [MetaCubeX/Clash.Meta#725]
panic: runtime error: slice bounds out of range [:4118] with capacity 4096

goroutine 8533090 [running]:
bufio.(*Reader).Read(0xc001930900, {0xc0016122a8?, 0x2?, 0x2?})
        /usr/local/go/src/bufio/bufio.go:250 +0x2f8
github.com/gorilla/websocket.(*messageReader).Read(0xc0015dc060, {0xc0016122a8, 0x2, 0x2})
        /go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1050 +0x1de
github.com/Dreamacro/clash/transport/vmess.(*websocketConn).Read(0xc00060bf40, {0xc0016122a8, 0x2, 0x2})
        /source/transport/vmess/websocket.go:73 +0x102
github.com/sagernet/sing/common/bufio/deadline.(*fallbackReader).Read(0xc0003814b0, {0xc0016122a8, 0x2, 0x2})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/deadline/reader_fallback.go:35 +0x1ad
github.com/sagernet/sing/common/bufio/deadline.(*Conn).Read(0x0?, {0xc0016122a8?, 0xc00026f7d0?, 0x520692?})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/deadline/conn.go:32 +0x27
io.ReadAtLeast({0x227ef37cbb8, 0xc000215460}, {0xc0016122a8, 0x2, 0x2}, 0x2)
        /usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:351
encoding/binary.Read({0x227ef37cbb8, 0xc000215460}, {0x168e0b0, 0x1efb140}, {0x1274720?, 0xc0016122a6})
        /usr/local/go/src/encoding/binary/binary.go:233 +0xc8
github.com/metacubex/sing-vmess.(*StreamChunkReader).Read(0xc002184990, {0xc002e98000, 0x8000, 0x8000})
        /go/pkg/mod/github.com/metacubex/sing-vmess@v0.1.8-0.20230801054944-603005461ff8/chunk_length_stream.go:36 +0x89
github.com/sagernet/sing/common/bufio.(*ExtendedReaderWrapper).ReadBuffer(0x4df20a?, 0xc0021b90e0)
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/conn.go:78 +0x5d
github.com/metacubex/sing-vmess.(*AEADReader).ReadBuffer(0xc002430ac0, 0xc0021b90e0)
        /go/pkg/mod/github.com/metacubex/sing-vmess@v0.1.8-0.20230801054944-603005461ff8/chunk_aead.go:54 +0x35
github.com/sagernet/sing/common/bufio.(*ChunkReader).ReadBuffer(0x30?, 0x140c020?)
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/chunk.go:26 +0x150
github.com/metacubex/sing-vmess.(*clientConn).ReadBuffer(0xc0020188c0?, 0xc0020188c0?)
        /go/pkg/mod/github.com/metacubex/sing-vmess@v0.1.8-0.20230801054944-603005461ff8/client.go:451 +0x4a
github.com/sagernet/sing/common/bufio.CopyExtendedWithPool({0x1679da0?, 0xc00014e5c0}, {0x1682398?, 0xc000381670}, {0x227ef73aff8, 0xc0020188c0}, {0xc001c069a0, 0x1, 0xc000381670?}, {0x0, ...})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/copy.go:181 +0x214
github.com/sagernet/sing/common/bufio.CopyExtended({0x1679da0, 0xc00014e5c0}, {0x1682398?, 0xc000381670?}, {0x227ef73aff8?, 0xc0020188c0}, {0xc001c069a0, 0x1, 0x1}, {0x0, ...})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/copy.go:93 +0x21b
github.com/sagernet/sing/common/bufio.Copy({0x1679da0, 0xc00014e5c0}, {0x227ef360368?, 0xc002225f20?})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/copy.go:72 +0x876
github.com/sagernet/sing/common/bufio.CopyConnContextList.func3({0x8e1b6f?, 0xc0025adf78?})
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/bufio/copy.go:235 +0x75
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/task/task.go:68 +0x84
created by github.com/sagernet/sing/common/task.(*Group).RunContextList
        /go/pkg/mod/github.com/metacubex/sing@v0.0.0-20230714010500-e24664dc75a7/common/task/task.go:67 +0x17e

**Comment by stevejohnson7** [comment]
请提供更多信息，比如如何复现
