### ISSUE TITLE
[Bug] `fatal error: sigaction failed` when trying to run on MediaTek MT7621AT

### ISSUE THREAD

**Issue by shvchk** [MetaCubeX/Clash.Meta#731]
I'm trying to run clash.meta on a [Fibertool FT-AIR-DUO-G](https://wikidevi.wi-cat.ru/Fibertool_FT-AIR-DUO-G) router. But even `clash-meta --help` results in a fatal error:

```
> ./clash-meta --help
fatal error: sigaction failed

runtime stack:
runtime.throw({0x12751b1, 0x10})
        runtime/panic.go:1077 +0x54 fp=0x7fffecd0 sp=0x7fffecbc pc=0x60f14
runtime.sysSigaction.func1()
        runtime/os_linux.go:560 +0x4c fp=0x7fffecdc sp=0x7fffecd0 pc=0x9fbf8
runtime.sysSigaction(0x80, 0x0, 0x7fffed0c)
        runtime/os_linux.go:559 +0x7c fp=0x7fffecf4 sp=0x7fffecdc pc=0x5d194
runtime.sigaction(...)
        runtime/sigaction.go:15
runtime.getsig(...)
        runtime/os_linux.go:526
runtime.initsig(0x0)
        runtime/signal_unix.go:134 +0x100 fp=0x7fffed30 sp=0x7fffecf4 pc=0x800d8
runtime.mstartm0()
        runtime/proc.go:1624 +0x70 fp=0x7fffed38 sp=0x7fffed30 pc=0x68e44
runtime.mstart1()
        runtime/proc.go:1596 +0x94 fp=0x7fffed48 sp=0x7fffed38 pc=0x68d3c
runtime.mstart0()
        runtime/proc.go:1557 +0x7c fp=0x7fffed5c sp=0x7fffed48 pc=0x68c88
runtime.mstart()
        runtime/asm_mipsx.s:89 +0x14 fp=0x7fffed60 sp=0x7fffed5c pc=0xa8b10

goroutine 1 [runnable]:
runtime.main()
        runtime/proc.go:144 fp=0x24487ec sp=0x24487ec pc=0x64c98
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x24487ec sp=0x24487ec pc=0xaaf44
```

How do I debug, what goes wrong (maybe I don't have some dependencies installed)?

```
> uname -a
Linux Wive-NG-HQ 3.4.114.313 #1 SMP 21042023 mips GNU/Linux
```

```
> lsmod
Module                  Size  Used by
wireguard             107199  0
ext4                  286191  1
mbcache                 5134  1 ext4
jbd2                   51198  1 ext4
usb_storage            31137  1
hw_nat                 19005  0
mt7615_ap            2139140  2
nf_nat_ftp              1121  0
nf_conntrack_ftp        5201  1 nf_nat_ftp
```

Steps to reproduce:

```sh
(
  v=1.15.1
  arch=mipsle-hardfloat
  url=https://github.com/MetaCubeX/Clash.Meta/releases/download/v${v}/clash.meta-linux-${arch}-v${v}.gz
  wget -qO- "$url" | gunzip -c > clash-meta
  chmod +x clash-meta
  ./clash-meta --help
)
```

Same issue with Clash reported 1.5 months ago: Dreamacro/clash#2842

**Comment by shvchk** [comment]
Tested with a hello world Go program, doesn't run. Therefore, it's definitely not a Clash's problem. Closing.
