### ISSUE TITLE
[Bug] http: panic serving 127.0.0.1:50374: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Jasonzyt** [MetaCubeX/Clash.Meta#797]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.16.0 windows amd64 with go1.21.1

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mode: rule
mixed-port: 7890
allow-lan: true
log-level: debug
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - 223.5.5.5
  nameserver:
  - tls://8.8.4.4#dns
  - tls://1.0.0.1#dns
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  nameserver-policy:
    geosite:cn,private:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
tun:
  enable: false
  stack: system
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
proxies:
- name: PROXY-HK
  type: vless
  server: ***
  port: ***
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
    short-id: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
- name: PROXY-US
  type: vless
  server: ***
  port: 8443
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
- name: PROXY-JP
  type: vless
  server: ***
  port: 8443
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
rules:
- DOMAIN-SUFFIX,bilibili.com,DIRECT,tcp
- DOMAIN-SUFFIX,openai.com,PROXY-US
- DOMAIN-SUFFIX,bing.com,PROXY-JP
- DOMAIN-SUFFIX,github.com,PROXY-HK
- DOMAIN-SUFFIX,google.com,PROXY-HK
- DST-PORT,123/136/137-139,DIRECT,udp
- GEOSITE,category-ads-all,REJECT
- GEOSITE,icloud@cn,DIRECT
- GEOSITE,apple@cn,DIRECT
- GEOSITE,apple-cn,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOSITE,facebook,PROXY-HK
- GEOSITE,youtube,PROXY-HK
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,geolocation-!cn,PROXY-HK
- GEOIP,telegram,PROXY-HK,no-resolve
- GEOIP,private,DIRECT,no-resolve
- GEOIP,cn,DIRECT
- MATCH,PROXY-HK
```

### Clash log

```shell
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve www.gstatic.com from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve *** from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve www.gstatic.com from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve www.gstatic.com from https://dns.alidns.com:443/dns-query"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="creating a new http client"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve *** from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="creating a new http client"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="[DNS] resolve www.gstatic.com from https://dns.alidns.com:443/dns-query"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[https://dns.alidns.com:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[https://doh.pub:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2023-10-15T12:47:41.622177+08:00" level=debug msg="creating a new http client"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[https://doh.pub:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[DNS] resolve doh.pub from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[DNS] resolve dns.alidns.com from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[DNS] resolve doh.pub from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6226861+08:00" level=debug msg="[DNS] resolve dns.alidns.com from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6464926+08:00" level=debug msg="[DNS] dns.alidns.com --> [223.6.6.6 223.5.5.5], from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6464926+08:00" level=debug msg="[DNS] dns.alidns.com --> [2400:3200:baba::1 2400:3200::1], from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6479897+08:00" level=debug msg="[DNS] doh.pub --> [], from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.6495651+08:00" level=debug msg="[DNS] doh.pub --> [1.12.12.12 120.53.53.53], from udp://223.5.5.5:53"
time="2023-10-15T12:47:41.7215705+08:00" level=debug msg="initial random HelloID:safari"
time="2023-10-15T12:47:41.7215705+08:00" level=debug msg="use specified fingerprint:Randomized"
2023/10/15 12:47:41 http: panic serving 127.0.0.1:50374: runtime error: invalid memory address or nil pointer dereference
goroutine 146 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x164ad80?, 0x1503e90?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/Dreamacro/clash/component/tls.GetRealityConn({0x19e2d40, 0xc0005a40e0}, {0x19e9e68, 0xc000092380}, {0xc00000baa0?, 0x0?}, 0xc0006051e0, 0xc0000379b0)
	/source/component/tls/reality.go:83 +0x628
github.com/Dreamacro/clash/transport/vmess.StreamTLSConn({0x19e2d40, 0xc0005a40e0}, {0x19e9e68?, 0xc000092380}, 0xc000434a18)
	/source/transport/vmess/tls.go:43 +0x18f
github.com/Dreamacro/clash/adapter/outbound.(*Vless).streamTLSConn(0xc0000a1300, {0x19e2d40, 0xc0005a40e0}, {0x19e9e68, 0xc000092380}, 0x0)
	/source/adapter/outbound/vless.go:223 +0x227
github.com/Dreamacro/clash/adapter/outbound.(*Vless).StreamConnContext(0xc0000a1300, {0x19e2d40?, 0xc0005a40e0?}, {0x19e9e68?, 0xc000092380?}, 0xc000043608?)
	/source/adapter/outbound/vless.go:164 +0x591
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContextWithDialer(0xc0000a1300, {0x19e2d40, 0xc0005a40e0}, {0x19d9718?, 0xc000880360?}, 0xc000300510?)
	/source/adapter/outbound/vless.go:268 +0x1a5
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContext(0xc0000a1300, {0x19e2d40, 0xc0005a40e0}, 0x0?, {0x0?, 0x0?, 0x0?})
	/source/adapter/outbound/vless.go:248 +0x2df
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(...)
	/source/adapter/adapter.go:67
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0000a1380, {0x19e2d40?, 0xc0005a40e0}, {0xc00046ddd0, 0x23}, {0x0?, 0x0, 0x0?}, 0x1)
	/source/adapter/adapter.go:252 +0x2e5
github.com/Dreamacro/clash/hub/route.getProxyDelay({0x19e0160, 0xc0002c6380}, 0xc00032a700)
	/source/hub/route/proxies.go:128 +0x274
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6380?}, 0xc0009342b6?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106ae0, {0x19e0160, 0xc0002c6380}, 0xc00032a700)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0002c6380?}, 0xc00031e270?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.findProxyByName.func1({0x19e0160, 0xc0002c6380}, 0xc00032a600)
	/source/hub/route/proxies.go:58 +0x25f
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0002c6380?}, 0xc00031e240?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.parseProxyName.func1({0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/source/hub/route/proxies.go:42 +0x1b6
net/http.HandlerFunc.ServeHTTP(0xc0003c8960?, {0x19e0160?, 0xc0002c6380?}, 0xc000435670?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106ae0, {0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6380?}, 0xc0009342c0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106a80, {0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc0003c8960?, {0x19e0160?, 0xc0002c6380?}, 0xc000435830?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106a80, {0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x0?, {0x19e0160?, 0xc0002c6380?}, 0x13aa737?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.authentication.func1({0x19e0160?, 0xc0002c6380?}, 0x1?)
	/source/hub/route/server.go:164 +0x25b
net/http.HandlerFunc.ServeHTTP(0xc0001f9ea0?, {0x19e0160?, 0xc0002c6380?}, 0xc00031e220?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6380?}, 0xc0000a6424?)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31 +0x26
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106840, {0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc00013c460?, {0x19e0160?, 0xc0002c6380?}, 0xc00032a500?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x19e0160, 0xc0002c6380}, 0xc00032a500)
	/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x17e
net/http.HandlerFunc.ServeHTTP(0x19e2cd0?, {0x19e0160?, 0xc0002c6380?}, 0x1506730?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106840, {0x19e0160, 0xc0002c6380}, 0xc002590a00)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x315
net/http.serverHandler.ServeHTTP({0xc00057e540?}, {0x19e0160?, 0xc0002c6380?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0003a6120, {0x19e2c98, 0xc0003c8390})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 54
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
time="2023-10-15T12:47:41.7391723+08:00" level=debug msg="[DNS] www.gstatic.com --> [], from https://dns.alidns.com:443/dns-query"
time="2023-10-15T12:47:41.7391723+08:00" level=debug msg="[DNS] www.gstatic.com --> [203.208.50.34], from https://dns.alidns.com:443/dns-query"
time="2023-10-15T12:47:41.7669032+08:00" level=debug msg="use specified fingerprint:Randomized"
2023/10/15 12:47:41 http: panic serving 127.0.0.1:50373: runtime error: invalid memory address or nil pointer dereference
goroutine 44 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x164ad80?, 0x1503e90?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/Dreamacro/clash/component/tls.GetRealityConn({0x19e2d40, 0xc0004a4000}, {0x19e9e68, 0xc000360088}, {0xc00000b960?, 0x0?}, 0xc0006856c0, 0xc0000378f0)
	/source/component/tls/reality.go:83 +0x628
github.com/Dreamacro/clash/transport/vmess.StreamTLSConn({0x19e2d40, 0xc0004a4000}, {0x19e9e68?, 0xc000360088}, 0xc0003eaa18)
	/source/transport/vmess/tls.go:43 +0x18f
github.com/Dreamacro/clash/adapter/outbound.(*Vless).streamTLSConn(0xc0000a1200, {0x19e2d40, 0xc0004a4000}, {0x19e9e68, 0xc000360088}, 0x0)
	/source/adapter/outbound/vless.go:223 +0x227
github.com/Dreamacro/clash/adapter/outbound.(*Vless).StreamConnContext(0xc0000a1200, {0x19e2d40?, 0xc0004a4000?}, {0x19e9e68?, 0xc000360088?}, 0xc0000435d8?)
	/source/adapter/outbound/vless.go:164 +0x591
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContextWithDialer(0xc0000a1200, {0x19e2d40, 0xc0004a4000}, {0x19d9718?, 0xc0001070e0?}, 0xc000134870?)
	/source/adapter/outbound/vless.go:268 +0x1a5
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContext(0xc0000a1200, {0x19e2d40, 0xc0004a4000}, 0x0?, {0x0?, 0x0?, 0x0?})
	/source/adapter/outbound/vless.go:248 +0x2df
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(...)
	/source/adapter/adapter.go:67
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0000a1280, {0x19e2d40?, 0xc0004a4000}, {0xc0003b8060, 0x23}, {0x0?, 0x0, 0x0?}, 0x1)
	/source/adapter/adapter.go:252 +0x2e5
github.com/Dreamacro/clash/hub/route.getProxyDelay({0x19e0160, 0xc0003e0000}, 0xc0003f0200)
	/source/hub/route/proxies.go:128 +0x274
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0003e0000?}, 0xc00091f7f6?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106ae0, {0x19e0160, 0xc0003e0000}, 0xc0003f0200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0003e0000?}, 0xc0004940d0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.findProxyByName.func1({0x19e0160, 0xc0003e0000}, 0xc0003f0100)
	/source/hub/route/proxies.go:58 +0x25f
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0003e0000?}, 0xc0004940a0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.parseProxyName.func1({0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/source/hub/route/proxies.go:42 +0x1b6
net/http.HandlerFunc.ServeHTTP(0xc000308090?, {0x19e0160?, 0xc0003e0000?}, 0xc0003eb670?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106ae0, {0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0003e0000?}, 0xc00091f810?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106a80, {0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc000308090?, {0x19e0160?, 0xc0003e0000?}, 0xc0003eb830?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106a80, {0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x0?, {0x19e0160?, 0xc0003e0000?}, 0x13aa737?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.authentication.func1({0x19e0160?, 0xc0003e0000?}, 0x1?)
	/source/hub/route/server.go:164 +0x25b
net/http.HandlerFunc.ServeHTTP(0xc0001f9ea0?, {0x19e0160?, 0xc0003e0000?}, 0xc000494080?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x1641500?, {0x19e0160?, 0xc0003e0000?}, 0xc0005c4064?)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31 +0x26
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106840, {0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc00013c460?, {0x19e0160?, 0xc0003e0000?}, 0xc0003f0000?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x19e0160, 0xc0003e0000}, 0xc0003f0000)
	/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x17e
net/http.HandlerFunc.ServeHTTP(0x19e2cd0?, {0x19e0160?, 0xc0003e0000?}, 0x1506730?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106840, {0x19e0160, 0xc0003e0000}, 0xc00029c000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x315
net/http.serverHandler.ServeHTTP({0xc0002841b0?}, {0x19e0160?, 0xc0003e0000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000300090, {0x19e2c98, 0xc0003c8390})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 54
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
time="2023-10-15T12:47:42.221434+08:00" level=debug msg="[DNS] *** --> [], from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:42.3294125+08:00" level=debug msg="[DNS] *** --> [***], from https://doh.pub:443/dns-query"
time="2023-10-15T12:47:42.37983+08:00" level=debug msg="use specified fingerprint:Randomized"
2023/10/15 12:47:42 http: panic serving 127.0.0.1:50372: runtime error: invalid memory address or nil pointer dereference
goroutine 65 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x164ad80?, 0x1503e90?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/Dreamacro/clash/component/tls.GetRealityConn({0x19e2d40, 0xc0005a4000}, {0x19e9e68, 0xc0003600a0}, {0xc00000b800?, 0x0?}, 0xc000685a00, 0xc000037830)
	/source/component/tls/reality.go:83 +0x628
github.com/Dreamacro/clash/transport/vmess.StreamTLSConn({0x19e2d40, 0xc0005a4000}, {0x19e9e68?, 0xc0003600a0}, 0xc0003eea18)
	/source/transport/vmess/tls.go:43 +0x18f
github.com/Dreamacro/clash/adapter/outbound.(*Vless).streamTLSConn(0xc0000a10c0, {0x19e2d40, 0xc0005a4000}, {0x19e9e68, 0xc0003600a0}, 0x0)
	/source/adapter/outbound/vless.go:223 +0x227
github.com/Dreamacro/clash/adapter/outbound.(*Vless).StreamConnContext(0xc0000a10c0, {0x19e2d40?, 0xc0005a4000?}, {0x19e9e68?, 0xc0003600a0?}, 0xc0000435a8?)
	/source/adapter/outbound/vless.go:164 +0x591
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContextWithDialer(0xc0000a10c0, {0x19e2d40, 0xc0005a4000}, {0x19d9718?, 0xc000880240?}, 0xc000300240?)
	/source/adapter/outbound/vless.go:268 +0x1a5
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContext(0xc0000a10c0, {0x19e2d40, 0xc0005a4000}, 0x0?, {0x0?, 0x0?, 0x0?})
	/source/adapter/outbound/vless.go:248 +0x2df
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(...)
	/source/adapter/adapter.go:67
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0000a1140, {0x19e2d40?, 0xc0005a4000}, {0xc00046dce0, 0x23}, {0x0?, 0x0, 0x0?}, 0x1)
	/source/adapter/adapter.go:252 +0x2e5
github.com/Dreamacro/clash/hub/route.getProxyDelay({0x19e0160, 0xc0002c6000}, 0xc00032a400)
	/source/hub/route/proxies.go:128 +0x274
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6000?}, 0xc000934206?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106ae0, {0x19e0160, 0xc0002c6000}, 0xc00032a400)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0002c6000?}, 0xc00031e150?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.findProxyByName.func1({0x19e0160, 0xc0002c6000}, 0xc00032a300)
	/source/hub/route/proxies.go:58 +0x25f
net/http.HandlerFunc.ServeHTTP(0x19e2c98?, {0x19e0160?, 0xc0002c6000?}, 0xc00031e120?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.parseProxyName.func1({0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/source/hub/route/proxies.go:42 +0x1b6
net/http.HandlerFunc.ServeHTTP(0xc0003c8750?, {0x19e0160?, 0xc0002c6000?}, 0xc0003ef670?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106ae0, {0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6000?}, 0xc000934210?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106a80, {0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc0003c8750?, {0x19e0160?, 0xc0002c6000?}, 0xc0003ef830?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106a80, {0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb
net/http.HandlerFunc.ServeHTTP(0x0?, {0x19e0160?, 0xc0002c6000?}, 0x13aa737?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/Dreamacro/clash/hub/route.authentication.func1({0x19e0160?, 0xc0002c6000?}, 0x1?)
	/source/hub/route/server.go:164 +0x25b
net/http.HandlerFunc.ServeHTTP(0xc0001f9ea0?, {0x19e0160?, 0xc0002c6000?}, 0xc00057e2a0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x1641500?, {0x19e0160?, 0xc0002c6000?}, 0xc0000a6364?)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31 +0x26
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000106840, {0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2ba
net/http.HandlerFunc.ServeHTTP(0xc00013c460?, {0x19e0160?, 0xc0002c6000?}, 0xc00032a200?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x19e0160, 0xc0002c6000}, 0xc00032a200)
	/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x17e
net/http.HandlerFunc.ServeHTTP(0x19e2cd0?, {0x19e0160?, 0xc0002c6000?}, 0x1506730?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000106840, {0x19e0160, 0xc0002c6000}, 0xc00032a000)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x315
net/http.serverHandler.ServeHTTP({0xc0003c8600?}, {0x19e0160?, 0xc0002c6000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0003a6000, {0x19e2c98, 0xc0003c8390})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 54
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
```

### Description

Using clash-verge

**Comment by Jasonzyt** [comment]
鉴定为玄学问题，时不时出现

**Comment by Jasonzyt** [comment]
它又出现了，而且不是只有我这样

**Comment by wwqgtxx** [comment]
加了个容错
https://github.com/MetaCubeX/Clash.Meta/commit/875561891064ee1983adfe93d0c39931a66bf48a

**Comment by Jasonzyt** [comment]
问题具有偶然性，时好时坏，无法得出复现方法
